### ISSUE TITLE
Potential compatibility with Sublime 3

### ISSUE THREAD

**Issue by cyenko** [komsit37/sublime-q-2#1]
Hi @komsit37,

Thanks for your work on sublime-q. You've mentioned that the repo is only compatible with Sublime 2, and I'm curious to see if I can port to Sublime 3. I wanted to know before I started if there are any glaring incompatibilities with Sublime 3 (and Python 3.3) before I start. Do you know of any?

Thanks,
Christian

**Comment by komsit37** [comment]
Hi Christian,

I'm glad it's useful for you!

The limitation is within qPython library (q interface from python). sublime 3 uses python 3.3 but qpython only support 2.7 (see https://github.com/exxeleron/qPython)

Porting shouldn't be too difficult, you can replace qpython call (there aren't many) in https://github.com/komsit37/sublime-q/blob/master/sublime-q.py with
kdb.py here https://github.com/gartinian/kdbTwitter/blob/master/feed.py
another benefit is that, we may not need numpy anymore.

Komsit

**Comment by cyenko** [comment]
Hi Komsit,

Thanks for your reply. I might be missing something, but it seems to me that kdb.py comes from QPy (https://bitbucket.org/halotis/qpy/src/4f7220b34332c0bce1baee35f33e0a604a4db1d4?at=default). It seems like QPy is actually a predecessor to the qPython module you're using now, and that it supports only 2.7 (http://www.timestored.com/kdb-guides/python-api). What do you think?

Christian

**Comment by komsit37** [comment]
Ah could be. I'm not sure about that too. The easiest way is to try to load
it on python 3 :)
If it works, the plugin should work too

**Comment by komsit37** [comment]
Actually, just saw your link. Yes this might not work...

**Comment by komsit37** [comment]
qpython now works with python 3. I have updated the plugin here https://github.com/komsit37/sublime-q-3. It's a whole rewrite with new features and improve stability.
